---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: started
      tags:
        - clickhouse
        - start service

  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "/tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
        mode: '0644'
      with_items: "{{ clickhouse_packages }}"
      tags:
        - clickhouse
        - distr

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags:
        - update

    - name: Install clickhouse packages using dpkg
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
      changed_when: false
      tags:
        - clickhouse
        - install

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - clickhouse
        - start service

    - name: Wait for clickhouse-server to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 9000
        delay: 10
        timeout: 300
      tags:
        - clickhouse
        - wait

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags:
        - clickhouse
        - db

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restart service

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: '0644'
      tags:
        - vector
        - distr

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags:
        - update

    - name: Install vector
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
      changed_when: false
      tags:
        - vector
        - install

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Start vector service
      tags:
        - vector
        - config

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - vector
        - restart service

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      tags:
        - restart service
        - nginx

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags:
        - update

    - name: Install Nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      tags:
        - install
        - nginx

    - name: Start Nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      tags:
        - service
        - nginx

    - name: Deploy Nginx configuration
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Restart Nginx
      tags:
        - config
        - nginx

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
      tags:
        - install
        - git

  tasks:
    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: "{{ repo_lighthouse }}"
        version: master
        dest: "{{ path_to_repo }}"
      tags:
        - git
        - clone

    - name: Deploy Lighthouse configuration
      ansible.builtin.template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: Restart Nginx
      tags:
        - config
        - nginx
