---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: https://github.com/RuslanArestov/vector-role.git
    scm: git
    version: "master"
    name: vector 